apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rollout.yaml
  - service.yaml
  - httproute.yaml

images:
  - name: ghcr.io/camcast3/walkthrough-server
    newTag: 7bca236ecbdf09db27c81286beb9c349a3034b6a
