apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: walkthrough-data
  namespace: walkthroughs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 1Gi
