apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: walkthrough-data
  namespace: walkthroughs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block   # Rook Ceph RBD block storage
  resources:
    requests:
      storage: 1Gi
